

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Google Tech
 */
package com.mycompany.database_pro;
public class goods_customer3 extends javax.swing.JFrame {

    /**
     * Creates new form goods_customer3
     */
    public goods_customer3() {
        initComponents();
        setSize(881,618);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        NEXT = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_3.jpg"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 30, 240, 160);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_11.jpg"))); // NOI18N
        getContentPane().add(jButton11);
        jButton11.setBounds(320, 30, 230, 160);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_110.jpg"))); // NOI18N
        getContentPane().add(jButton10);
        jButton10.setBounds(600, 30, 230, 160);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz__24.jpg"))); // NOI18N
        getContentPane().add(jButton12);
        jButton12.setBounds(30, 300, 240, 160);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz__15.jpg"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 300, 240, 160);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz__23.jpg"))); // NOI18N
        getContentPane().add(jButton13);
        jButton13.setBounds(600, 300, 240, 160);

        NEXT.setBackground(new java.awt.Color(204, 204, 204));
        NEXT.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        getContentPane().add(NEXT);
        NEXT.setBounds(770, 580, 90, 32);

        BACK.setBackground(new java.awt.Color(204, 204, 204));
        BACK.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK);
        BACK.setBounds(10, 580, 90, 32);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("    Name : UTU OFFICE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(640, 470, 190, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("    Name : LEXUS SOFA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 470, 190, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("  Name : WORKSTATION OFFICE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 470, 220, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("    Name : KEPOS OFFICE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 200, 190, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("    Name : ADA SOFA");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 200, 190, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("    Name : RESEPTION OFFICE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(630, 200, 190, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("    Color : YELLGRA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 500, 190, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("    Color : BLAK2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 500, 190, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("    Color : MELTON");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 500, 190, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("    Color : GRAIS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 230, 190, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("    Color : BLACK2");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 230, 190, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("    Color : GRAIBRO");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(650, 230, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_color.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -4, 880, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
          dispose();// to close the curent frame
        customerFrame G2 = new customerFrame();// next GUI....
        G2.setVisible(true); 
    }//GEN-LAST:event_NEXTActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
   dispose();// to close the curent frame
        goods_customer2 G3 = new goods_customer2();// next GUI....
        G3.setVisible(true);  
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(goods_customer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(goods_customer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(goods_customer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(goods_customer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new goods_customer3().setVisible(true);
                 new goods_customer3().setSize(881,618);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton NEXT;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
