/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Google Tech
 */
package com.mycompany.database_pro;
public class goods_customer2 extends javax.swing.JFrame {

    /**
     * Creates new form goods_customer2
     */
    public goods_customer2() {
        initComponents();
        setSize(884,621);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        NEXT = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(884, 618));
        getContentPane().setLayout(null);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_9_1.jpg"))); // NOI18N
        getContentPane().add(jButton9);
        jButton9.setBounds(320, 290, 230, 160);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_112.jpg"))); // NOI18N
        getContentPane().add(jButton12);
        jButton12.setBounds(320, 30, 230, 160);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_7.jpg"))); // NOI18N
        getContentPane().add(jButton7);
        jButton7.setBounds(620, 30, 230, 160);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz__18.jpg"))); // NOI18N
        getContentPane().add(jButton6);
        jButton6.setBounds(40, 290, 230, 160);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz__13.jpg"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 30, 230, 160);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz__16.jpg"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(620, 290, 230, 160);

        NEXT.setBackground(new java.awt.Color(204, 204, 204));
        NEXT.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        getContentPane().add(NEXT);
        NEXT.setBounds(790, 580, 90, 32);

        BACK.setBackground(new java.awt.Color(204, 204, 204));
        BACK.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK);
        BACK.setBounds(10, 580, 90, 32);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("    Name : WID OFFICE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(650, 460, 190, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("    Name : DIVAV OFFICE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(350, 460, 190, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("    Name : ADA OFFICE");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 460, 190, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("    Name : TAB OFFICE");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 200, 190, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("    Name :  LUXURIOS  OFFICE");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(640, 200, 190, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("    Name : AHLAS OFFICE");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(340, 200, 190, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("    Color : MELTON");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(660, 490, 190, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("    Color : MELTON");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(360, 490, 190, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("    Color : HONEY");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(70, 490, 190, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("    Color : BROS");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(60, 230, 190, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("    Color : BLACK2");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(650, 230, 190, 30);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("    Color : DARK BROUN");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(350, 230, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_color.jpeg"))); // NOI18N
        jLabel1.setPreferredSize(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -4, 890, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
       dispose();// to close the curent frame
        goods_customer3 G3 = new goods_customer3();// next GUI....
        G3.setVisible(true);     
    }//GEN-LAST:event_NEXTActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        dispose();// to close the curent frame
        goods_customer G2 = new goods_customer();// next GUI....
        G2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(goods_customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(goods_customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(goods_customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(goods_customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new goods_customer2().setVisible(true);
                 new goods_customer2().setSize(884,621);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton NEXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    // End of variables declaration//GEN-END:variables
}
