/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.database_pro;

//import goods_customer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import location;

/**
 *
 * @author Dell
 */
public class Main_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Main_Screen
     */
    public Main_Screen() {
        initComponents();
    }
/*public class home extends javax.swing.JPanel{
    public void paintCompnent(Graphic g){
    ImageIcon f=new ImageIcon("C:\\Users\\Google Tech\\Desktop");
    g.drawImage(f.getImage(),WIDTH,WIDTH,this );
    }*/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        INFORMATION = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PASSW = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel6.setLayout(null);

        jButton3.setBackground(new java.awt.Color(255, 153, 51));
        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(810, 570, 90, 30);

        jTabbedPane2.addTab("CUSTOMER WINDOW", jPanel6);

        jPanel1.setLayout(null);

        INFORMATION.setBackground(new java.awt.Color(51, 51, 51));
        INFORMATION.setFont(new java.awt.Font("Kristen ITC", 1, 17)); // NOI18N
        INFORMATION.setForeground(new java.awt.Color(255, 255, 255));
        INFORMATION.setText("more");
        INFORMATION.setToolTipText("");
        INFORMATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFORMATIONActionPerformed(evt);
            }
        });
        jPanel1.add(INFORMATION);
        INFORMATION.setBounds(740, 580, 182, 45);

        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("WELCOME TO PRADO");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 70, 620, 90);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Our Location ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(400, 580, 182, 45);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Connect with us ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(70, 580, 182, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_56710ead-a88e-4711-92b7-fe4f6be06db2 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-3, 0, 1030, 670);

        jTabbedPane2.addTab("HOME WINDOW  ", jPanel1);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0,0,0,70));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel4.setText("      LOGIN");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(151, 70, 232, 48);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("USER NAME");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(150, 190, 90, 20);
        jPanel2.add(USER);
        USER.setBounds(139, 220, 228, 35);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 300, 90, 20);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(200, 460, 110, 30);

        PASSW.setText("jPasswordField1");
        jPanel2.add(PASSW);
        PASSW.setBounds(140, 340, 228, 34);
        PASSW.getAccessibleContext().setAccessibleName("");

        jPanel5.add(jPanel2);
        jPanel2.setBounds(90, 0, 550, 660);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOCK.png"))); // NOI18N
        jPanel5.add(jLabel7);
        jLabel7.setBounds(670, 0, 350, 660);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jLabel8);
        jLabel8.setBounds(87, -4, 940, 670);

        jTabbedPane2.addTab("ADMIN WINDOW ", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INFORMATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFORMATIONActionPerformed
       dispose();// to close the curent frame
                    INFORMATION_FRAME IF = new INFORMATION_FRAME();// next GUI....
                    IF.setVisible(true);
                    // TODO add your handling code here:
    }//GEN-LAST:event_INFORMATIONActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       dispose();// to close the curent frame
                    goods_customer GC = new goods_customer();// next GUI....
                    GC.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
         String password = "09$0049";
         String user_name ="ADMIN OF BRADO";
                if ( USER.getText().equals(user_name) && PASSW.getText().equals(password))
            {
             dispose();// to close the curent frame
            ADMIN_FRAME aa = new ADMIN_FRAME();// next GUI....
            aa.setVisible(true); 
            
            }
                else {
                    // Password is incorrect, show JOptionPane message
                    JOptionPane.showMessageDialog(null, "Incorrect Password. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                    PASSW.setText("");
                    USER.setText("");
                    
                }
            
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         dispose();// to close the curent frame
                    OURLOCATION  u = new OURLOCATION();// next GUI.... 
                    u.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();// to close the curent frame
        Connect  con = new Connect();// next GUI.... 
         con.setVisible(true);  
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INFORMATION;
    private javax.swing.JPasswordField PASSW;
    private javax.swing.JTextField USER;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

    static class home {

        public home() {
        }
    }
}